# -*- coding: utf-8 -*-
# =============================================================================
# 中文阅读说明：RAG 核心模块，负责查询变换、召回、融合、重排、证据评估和上下文组装。
# 主要定义：QueryExpansionResult、QueryExpander。建议先从公开入口函数开始，再沿调用关系向下阅读。
# =============================================================================
"""
rag_template/query/query_expander.py
====================================

RAG query expansion helpers.

This module owns the retrieval-time LLM query generation layer:
- RAG-Fusion: generate multiple semantically different retrieval queries.
- HyDE: generate a hypothetical answer/document and use it as an additional
  retrieval query.

The public output contract is intentionally stable because downstream retrieval,
RRF fusion, rerank, context packing, and data capture depend on it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from core.runtime.timing import MonotonicTimer, Timer, elapsed_ms
from core.runtime.execution_control import WorkflowExecutionCancelled
from model_gateway.call_boundary import ModelCallBudgetExceeded
from rag.ports.generation import TextGenerator


# 阅读注释（类）：封装 查询 expansion 结果，集中封装相关状态、依赖和行为。
@dataclass
class QueryExpansionResult:
    """Expanded query set for downstream retrieval."""

    original_query: str
    strategy: str = "hybrid"
    rewritten_queries: List[str] = field(default_factory=list)
    hyde_query: Optional[str] = None
    retrieval_queries: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    # Internal execution lineage only; intentionally excluded from to_dict().
    runtime_context: Dict[str, Any] = field(default_factory=dict)

    # 阅读注释（函数）：把 QueryExpansionResult 转换为 字典。
    def to_dict(self) -> Dict[str, Any]:
        """把 QueryExpansionResult 转换为 字典。

        返回:
            Dict[str, Any]
        """
        return {
            "original_query": self.original_query,
            "strategy": self.strategy,
            "rewritten_queries": self.rewritten_queries,
            "hyde_query": self.hyde_query,
            "retrieval_queries": self.retrieval_queries,
            "metadata": self.metadata,
        }


# 阅读注释（类）：封装 查询 expander，集中封装相关状态、依赖和行为。
class QueryExpander:
    """LLM-backed query expansion for RAG-Fusion and HyDE.

    Args:
        llm_generator: Any object exposing generate(prompt, **kwargs) -> str.
            Production composition injects a ModelGateway-backed adapter.
        use_llm: If True, RAG-Fusion / HyDE are generated by the LLM. If the LLM
            is unavailable or fails, deterministic fallback keeps the pipeline
            runnable and records the fallback reason in metadata.
        generation_params: Default generation parameters for query expansion.
    """

    # 阅读注释（函数）：初始化 QueryExpander，保存运行所需的依赖、配置或状态。
    def __init__(
        self,
        *,
        llm_generator: Optional[TextGenerator] = None,
        use_llm: bool = True,
        generation_params: Optional[Dict[str, Any]] = None,
        fallback_to_deterministic: bool = True,
        timer: Timer | None = None,
    ):
        """初始化 QueryExpander，保存运行所需的依赖、配置或状态。

        参数:
            llm_generator: LLM generator，具体约束请结合类型标注和调用方确认。
            use_llm: use LLM，具体约束请结合类型标注和调用方确认。
            generation_params: 生成 params，具体约束请结合类型标注和调用方确认。
            fallback_to_deterministic: fallback to deterministic，具体约束请结合类型标注和调用方确认。
            timer: timer，具体约束请结合类型标注和调用方确认。

        返回:
            未显式标注；请结合调用方和实际返回语句理解。

        阅读提示:
            主要直接调用：bool, dict, MonotonicTimer。
        """
        self.llm_generator = llm_generator
        self.use_llm = bool(use_llm)
        self.generation_params = dict(generation_params or {})
        self.fallback_to_deterministic = bool(fallback_to_deterministic)
        self.timer = timer or MonotonicTimer()

    # 阅读注释（函数）：处理 dedup keep order 相关逻辑。
    @staticmethod
    def _dedup_keep_order(items: List[str]) -> List[str]:
        """处理 dedup keep order 相关逻辑。

        参数:
            items: 待处理的数据项集合。

        返回:
            List[str]

        阅读提示:
            主要直接调用：set, strip, str, text.lower, seen.add, output.append。
        """
        seen = set()
        output: List[str] = []
        for item in items:
            text = str(item or "").strip()
            if not text:
                continue
            key = text.lower()
            if key in seen:
                continue
            seen.add(key)
            output.append(text)
        return output


    # 阅读注释（函数）：处理 dedup keep order 相关逻辑。
    @staticmethod
    def dedup_keep_order(items: List[str]) -> List[str]:
        """Public compatibility helper used by query-transformer plugins."""
        return QueryExpander._dedup_keep_order(items)

    # 阅读注释（函数）：改写 查询集合。
    def rewrite_queries(
        self,
        *,
        query: str,
        num_rewrites: int,
        runtime_context: Dict[str, Any] | None = None,
    ) -> tuple[List[str], Dict[str, Any]]:
        """Generate query rewrites without interpreting a strategy string."""
        return self._rewrite_queries(
            query=query,
            num_rewrites=num_rewrites,
            runtime_context=runtime_context,
        )

    # 阅读注释（函数）：构建 hypothetical 文档。
    def build_hypothetical_document(
        self,
        *,
        query: str,
        runtime_context: Dict[str, Any] | None = None,
    ) -> tuple[Optional[str], Dict[str, Any]]:
        """Generate one HyDE document without interpreting a strategy string."""
        return self._build_hypothetical_document(
            query=query,
            runtime_context=runtime_context,
        )

    # 阅读注释（函数）：处理 LLM available 相关逻辑。
    def _llm_available(self) -> bool:
        """处理 LLM available 相关逻辑。

        返回:
            bool

        阅读提示:
            主要直接调用：bool。
        """
        return bool(self.use_llm and self.llm_generator is not None)

    # 阅读注释（函数）：处理 call LLM 相关逻辑。
    def _call_llm(
        self,
        prompt: str,
        *,
        system_prompt: str,
        max_new_tokens: int,
        temperature: float = 0.1,
        top_p: float = 0.9,
        do_sample: bool = False,
        call_purpose: str = "rag_query_transform",
        runtime_context: Dict[str, Any] | None = None,
    ) -> str:
        """处理 call LLM 相关逻辑。

        参数:
            prompt: 提示词，具体约束请结合类型标注和调用方确认。
            system_prompt: system 提示词，具体约束请结合类型标注和调用方确认。
            max_new_tokens: max new tokens，具体约束请结合类型标注和调用方确认。
            temperature: temperature，具体约束请结合类型标注和调用方确认。
            top_p: top p，具体约束请结合类型标注和调用方确认。
            do_sample: do sample，具体约束请结合类型标注和调用方确认。

        返回:
            str

        阅读提示:
            主要直接调用：RuntimeError, dict, params.pop, params.setdefault, self.llm_generator.generate, isinstance, str, text.strip。
        """
        if self.llm_generator is None:
            raise RuntimeError("llm_generator is not configured")

        params = dict(self.generation_params)
        # Internal routing-only parameters must not be forwarded to transformers.generate().
        params.pop("rewrite_max_new_tokens", None)
        params.pop("hyde_max_new_tokens", None)
        params.setdefault("max_new_tokens", max_new_tokens)
        params.setdefault("temperature", temperature)
        params.setdefault("top_p", top_p)
        params.setdefault("do_sample", do_sample)

        try:
            text = self.llm_generator.generate(
                prompt,
                system_prompt=system_prompt,
                call_purpose=call_purpose,
                runtime_context=runtime_context,
                **params,
            )
        except TypeError:
            # Compatibility for very small fake generators that only accept prompt.
            text = self.llm_generator.generate(f"{system_prompt}\n\n{prompt}", **params)

        if not isinstance(text, str):
            text = str(text)
        return text.strip()

    # 阅读注释（函数）：处理 clean line 相关逻辑。
    @staticmethod
    def _clean_line(text: str) -> str:
        """处理 clean line 相关逻辑。

        参数:
            text: 待处理文本。

        返回:
            str

        阅读提示:
            主要直接调用：strip, str, re.sub, text.strip。
        """
        text = str(text or "").strip()
        text = re.sub(r"^\s*[-*•]+\s*", "", text)
        text = re.sub(r"^\s*\d+[).、：:]\s*", "", text)
        text = text.strip(" \t\r\n'\"`，。；;")
        return text.strip()

    # 阅读注释（函数）：解析 改写 输出。
    def _parse_rewrite_output(self, raw_text: str, *, original_query: str, num_rewrites: int) -> List[str]:
        """解析 改写 输出。

        参数:
            raw_text: raw 文本，具体约束请结合类型标注和调用方确认。
            original_query: original 查询，具体约束请结合类型标注和调用方确认。
            num_rewrites: num rewrites，具体约束请结合类型标注和调用方确认。

        返回:
            List[str]

        阅读提示:
            主要直接调用：splitlines, str, self._clean_line, line.startswith, line.endswith, line.strip, any, len。
        """
        lines = []
        for raw_line in str(raw_text or "").splitlines():
            line = self._clean_line(raw_line)
            if not line:
                continue
            if line.startswith("[") and line.endswith("]"):
                line = self._clean_line(line.strip("[]"))
            if any(x in line for x in ("以下", "查询改写", "改写结果", "输出", "答案")) and len(line) < 30:
                continue
            lines.append(line)

        if len(lines) <= 1:
            # Some local models ignore line breaks. Split common Chinese separators.
            pieces = re.split(r"[；;]|(?<=。)\s*", str(raw_text or ""))
            lines = [self._clean_line(x) for x in pieces if self._clean_line(x)]

        candidates = []
        for line in lines:
            if len(line) < 4:
                continue
            if line == original_query:
                continue
            candidates.append(line)
        return self._dedup_keep_order(candidates)[: max(0, int(num_rewrites))]

    # 阅读注释（函数）：改写 查询集合。
    def _rewrite_queries(
        self,
        query: str,
        num_rewrites: int,
        runtime_context: Dict[str, Any] | None = None,
    ) -> tuple[List[str], Dict[str, Any]]:
        """改写 查询集合。

        参数:
            query: 当前检索或生成查询。
            num_rewrites: num rewrites，具体约束请结合类型标注和调用方确认。

        返回:
            tuple[List[str], Dict[str, Any]]

        阅读提示:
            主要直接调用：self._llm_available, max, int, self.timer.now, self._call_llm, self.generation_params.get, elapsed_ms, self._parse_rewrite_output。
        """
        meta: Dict[str, Any] = {
            "method": "llm" if self._llm_available() else "deterministic_fallback",
            "latency_ms": None,
            "raw_output": None,
            "fallback_used": False,
            "fallback_reason": None,
        }
        requested = max(0, int(num_rewrites))
        if requested <= 0:
            return [], meta

        if self._llm_available():
            system_prompt = "你是企业级 RAG 检索查询改写器。你的任务是生成检索查询，不是回答问题。"
            prompt = (
                "请为下面的用户问题生成 RAG-Fusion 使用的检索查询改写。\n"
                "要求：\n"
                f"1. 生成 {requested} 条。\n"
                "2. 每条查询覆盖不同检索视角，例如业务需求、架构模块、流程阶段、验收标准、风险合规。\n"
                "3. 保留原问题核心实体，不要编造具体事实。\n"
                "4. 每行只输出一条查询，不要编号，不要解释。\n\n"
                f"用户问题：{query}"
            )
            try:
                t0 = self.timer.now()
                raw = self._call_llm(
                    prompt,
                    system_prompt=system_prompt,
                    max_new_tokens=int(self.generation_params.get("rewrite_max_new_tokens", max(96, requested * 64))),
                    temperature=0.1,
                    top_p=0.9,
                    do_sample=False,
                    call_purpose="rag_query_rewrite",
                    runtime_context=runtime_context,
                )
                meta["latency_ms"] = elapsed_ms(self.timer, t0)
                meta["raw_output"] = raw
                rewrites = self._parse_rewrite_output(raw, original_query=query, num_rewrites=requested)
                if rewrites:
                    meta["parsed_count"] = len(rewrites)
                    return rewrites, meta
                raise ValueError("LLM rewrite output produced no valid query")
            except (ModelCallBudgetExceeded, WorkflowExecutionCancelled):
                raise
            except Exception as exc:
                if not self.fallback_to_deterministic:
                    raise
                meta["fallback_used"] = True
                meta["fallback_reason"] = f"{exc.__class__.__name__}: {exc}"

        rewrites = self._deterministic_rewrite_queries(query=query, num_rewrites=requested)
        meta["method"] = "deterministic_fallback"
        meta["parsed_count"] = len(rewrites)
        return rewrites, meta

    # 阅读注释（函数）：构建 hypothetical 文档。
    def _build_hypothetical_document(
        self,
        query: str,
        runtime_context: Dict[str, Any] | None = None,
    ) -> tuple[Optional[str], Dict[str, Any]]:
        """构建 hypothetical 文档。

        参数:
            query: 当前检索或生成查询。

        返回:
            tuple[Optional[str], Dict[str, Any]]

        阅读提示:
            主要直接调用：self._llm_available, self.timer.now, self._call_llm, int, self.generation_params.get, elapsed_ms, self._clean_hyde_output, len。
        """
        meta: Dict[str, Any] = {
            "method": "llm" if self._llm_available() else "deterministic_fallback",
            "latency_ms": None,
            "raw_output": None,
            "fallback_used": False,
            "fallback_reason": None,
        }

        if self._llm_available():
            system_prompt = "你是 HyDE 假想文档生成器。你的任务是生成用于检索的假想资料，不是最终回答。"
            prompt = (
                "请根据用户问题生成一段 HyDE 假想文档，用于向量检索。\n"
                "要求：\n"
                "1. 写成一段企业知识库资料风格的中文文本。\n"
                "2. 覆盖可能相关的概念、流程、模块、验收、风险、引用依据。\n"
                "3. 不要声称具体项目事实已经存在，不要输出引用编号。\n"
                "4. 长度控制在 200 到 350 个汉字。\n"
                "5. 只输出假想文档正文，不要解释。\n\n"
                f"用户问题：{query}"
            )
            try:
                t0 = self.timer.now()
                raw = self._call_llm(
                    prompt,
                    system_prompt=system_prompt,
                    max_new_tokens=int(self.generation_params.get("hyde_max_new_tokens", 256)),
                    temperature=0.1,
                    top_p=0.9,
                    do_sample=False,
                    call_purpose="rag_hyde",
                    runtime_context=runtime_context,
                )
                meta["latency_ms"] = elapsed_ms(self.timer, t0)
                meta["raw_output"] = raw
                hyde = self._clean_hyde_output(raw)
                if hyde:
                    meta["char_count"] = len(hyde)
                    return hyde, meta
                raise ValueError("LLM HyDE output is empty")
            except (ModelCallBudgetExceeded, WorkflowExecutionCancelled):
                raise
            except Exception as exc:
                if not self.fallback_to_deterministic:
                    raise
                meta["fallback_used"] = True
                meta["fallback_reason"] = f"{exc.__class__.__name__}: {exc}"

        hyde = self._deterministic_hypothetical_document(query)
        meta["method"] = "deterministic_fallback"
        meta["char_count"] = len(hyde)
        return hyde, meta

    # 阅读注释（函数）：处理 clean hyde 输出 相关逻辑。
    @staticmethod
    def _clean_hyde_output(raw_text: str) -> str:
        """处理 clean hyde 输出 相关逻辑。

        参数:
            raw_text: raw 文本，具体约束请结合类型标注和调用方确认。

        返回:
            str

        阅读提示:
            主要直接调用：strip, str, re.sub, text.strip。
        """
        text = str(raw_text or "").strip()
        text = re.sub(r"^\s*(HyDE|假想文档|假设文档|正文)\s*[:：]\s*", "", text, flags=re.IGNORECASE)
        text = text.strip(" \t\r\n'\"`")
        return text

    # 阅读注释（函数）：处理 deterministic 改写 查询集合 相关逻辑。
    def _deterministic_rewrite_queries(self, query: str, num_rewrites: int) -> List[str]:
        """处理 deterministic 改写 查询集合 相关逻辑。

        参数:
            query: 当前检索或生成查询。
            num_rewrites: num rewrites，具体约束请结合类型标注和调用方确认。

        返回:
            List[str]

        阅读提示:
            主要直接调用：tpl.format, self._dedup_keep_order, max, int。
        """
        templates = [
            "{q} 的背景、目标、范围、约束、输入输出和验收要求",
            "{q} 涉及的关键概念、组成部分、处理流程、依赖关系和边界条件",
            "{q} 的实施步骤、风险、合规要求、质量标准和待确认信息",
            "{q} 的相关事实、数据依据、历史案例、规范条款和可追溯证据",
            "{q} 的常见问题、异常处理、评估指标、运维要求和改进建议",
        ]
        rewrites = [tpl.format(q=query) for tpl in templates]
        return self._dedup_keep_order(rewrites[: max(0, int(num_rewrites))])

    # 阅读注释（函数）：处理 deterministic hypothetical 文档 相关逻辑。
    @staticmethod
    def _deterministic_hypothetical_document(query: str) -> str:
        """处理 deterministic hypothetical 文档 相关逻辑。

        参数:
            query: 当前检索或生成查询。

        返回:
            str
        """
        return (
            f"这是一段与问题《{query}》高度相关的知识资料。"
            f"资料可能包含背景、目标、范围、约束、关键概念、组成部分、处理流程、"
            f"输入输出、事实依据、规范条款、风险控制、质量标准、验收要求和实施建议。"
            f"内容应围绕问题本身展开，并区分已知事实、外部依据和待确认信息。"
        )
