# -*- coding: utf-8 -*-
"""
rag_template/query/query_expander.py
====================================

RAG query expansion helpers.

This module owns the retrieval-time LLM query generation layer:
- RAG-Fusion: generate multiple semantically different retrieval queries.
- HyDE: generate a hypothetical answer/document and use it as an additional
  retrieval query.

The public output contract is intentionally stable because downstream retrieval,
RRF fusion, rerank, context packing, and data capture depend on it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from core.runtime.timing import MonotonicTimer, Timer, elapsed_ms
from rag.ports.generation import TextGenerator


@dataclass
class QueryExpansionResult:
    """Expanded query set for downstream retrieval."""

    original_query: str
    strategy: str = "hybrid"
    rewritten_queries: List[str] = field(default_factory=list)
    hyde_query: Optional[str] = None
    retrieval_queries: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "original_query": self.original_query,
            "strategy": self.strategy,
            "rewritten_queries": self.rewritten_queries,
            "hyde_query": self.hyde_query,
            "retrieval_queries": self.retrieval_queries,
            "metadata": self.metadata,
        }


class QueryExpander:
    """LLM-backed query expansion for RAG-Fusion and HyDE.

    Args:
        llm_generator: Any object exposing generate(prompt, **kwargs) -> str.
            LocalLLMGenerator is the default implementation used by RAGTool.
        use_llm: If True, RAG-Fusion / HyDE are generated by the LLM. If the LLM
            is unavailable or fails, deterministic fallback keeps the pipeline
            runnable and records the fallback reason in metadata.
        generation_params: Default generation parameters for query expansion.
    """

    BASIC_STRATEGIES = {"", "default", "basic", "hybrid", "parent_child_hybrid"}
    RAG_FUSION_STRATEGIES = {"rag_fusion", "fusion"}
    HYDE_STRATEGIES = {"hyde"}
    COMBINED_STRATEGIES = {"rag_fusion_hyde", "hyde_fusion", "fusion_hyde"}

    def __init__(
        self,
        *,
        llm_generator: Optional[TextGenerator] = None,
        use_llm: bool = True,
        generation_params: Optional[Dict[str, Any]] = None,
        fallback_to_deterministic: bool = True,
        timer: Timer | None = None,
    ):
        self.llm_generator = llm_generator
        self.use_llm = bool(use_llm)
        self.generation_params = dict(generation_params or {})
        self.fallback_to_deterministic = bool(fallback_to_deterministic)
        self.timer = timer or MonotonicTimer()

    def expand(
        self,
        query: str,
        *,
        strategy: str = "hybrid",
        num_rewrites: int = 3,
        enable_hyde: Optional[bool] = None,
    ) -> QueryExpansionResult:
        query = str(query or "").strip()
        if not query:
            raise ValueError("query cannot be empty")

        normalized_strategy = str(strategy or "hybrid").strip().lower()
        if normalized_strategy in self.BASIC_STRATEGIES:
            normalized_strategy = "hybrid"

        rag_fusion_requested = (
            normalized_strategy in self.RAG_FUSION_STRATEGIES
            or normalized_strategy in self.COMBINED_STRATEGIES
        )
        hyde_requested = (
            normalized_strategy in self.HYDE_STRATEGIES
            or normalized_strategy in self.COMBINED_STRATEGIES
            or bool(enable_hyde)
        )

        metadata: Dict[str, Any] = {
            "expander": self.__class__.__name__,
            "num_rewrites_requested": int(num_rewrites),
            "rag_fusion_requested": bool(rag_fusion_requested),
            "hyde_requested": bool(hyde_requested),
            "llm_enabled": bool(self.use_llm and self.llm_generator is not None),
            "llm_model_name": self._infer_llm_name(),
            "fallback_to_deterministic": self.fallback_to_deterministic,
            "mode": "llm_query_expansion" if self.use_llm and self.llm_generator is not None else "deterministic_light",
        }

        rewritten_queries: List[str] = []
        hyde_query: Optional[str] = None
        retrieval_queries: List[str] = [query]

        if rag_fusion_requested:
            rewritten_queries, rewrite_meta = self._rewrite_queries(query=query, num_rewrites=num_rewrites)
            metadata["rag_fusion"] = rewrite_meta
            retrieval_queries.extend(rewritten_queries)

        if hyde_requested:
            hyde_query, hyde_meta = self._build_hypothetical_document(query=query)
            metadata["hyde"] = hyde_meta
            if hyde_query:
                retrieval_queries.append(hyde_query)

        retrieval_queries = self._dedup_keep_order(retrieval_queries)
        metadata["query_count"] = len(retrieval_queries)

        return QueryExpansionResult(
            original_query=query,
            strategy=normalized_strategy,
            rewritten_queries=rewritten_queries,
            hyde_query=hyde_query,
            retrieval_queries=retrieval_queries,
            metadata=metadata,
        )

    @staticmethod
    def _dedup_keep_order(items: List[str]) -> List[str]:
        seen = set()
        output: List[str] = []
        for item in items:
            text = str(item or "").strip()
            if not text:
                continue
            key = text.lower()
            if key in seen:
                continue
            seen.add(key)
            output.append(text)
        return output


    @staticmethod
    def dedup_keep_order(items: List[str]) -> List[str]:
        """Public compatibility helper used by query-transformer plugins."""
        return QueryExpander._dedup_keep_order(items)

    def rewrite_queries(
        self,
        *,
        query: str,
        num_rewrites: int,
    ) -> tuple[List[str], Dict[str, Any]]:
        """Generate query rewrites without interpreting a strategy string."""
        return self._rewrite_queries(query=query, num_rewrites=num_rewrites)

    def build_hypothetical_document(
        self,
        *,
        query: str,
    ) -> tuple[Optional[str], Dict[str, Any]]:
        """Generate one HyDE document without interpreting a strategy string."""
        return self._build_hypothetical_document(query=query)

    def _infer_llm_name(self) -> Optional[str]:
        llm = self.llm_generator
        if llm is None:
            return None
        for attr in ("model_name", "model_path", "model", "name"):
            value = getattr(llm, attr, None)
            if isinstance(value, str) and value.strip():
                return value
        return llm.__class__.__name__

    def _llm_available(self) -> bool:
        return bool(self.use_llm and self.llm_generator is not None)

    def _call_llm(
        self,
        prompt: str,
        *,
        system_prompt: str,
        max_new_tokens: int,
        temperature: float = 0.1,
        top_p: float = 0.9,
        do_sample: bool = False,
    ) -> str:
        if self.llm_generator is None:
            raise RuntimeError("llm_generator is not configured")

        params = dict(self.generation_params)
        # Internal routing-only parameters must not be forwarded to transformers.generate().
        params.pop("rewrite_max_new_tokens", None)
        params.pop("hyde_max_new_tokens", None)
        params.setdefault("max_new_tokens", max_new_tokens)
        params.setdefault("temperature", temperature)
        params.setdefault("top_p", top_p)
        params.setdefault("do_sample", do_sample)

        try:
            text = self.llm_generator.generate(prompt, system_prompt=system_prompt, **params)
        except TypeError:
            # Compatibility for very small fake generators that only accept prompt.
            text = self.llm_generator.generate(f"{system_prompt}\n\n{prompt}", **params)

        if not isinstance(text, str):
            text = str(text)
        return text.strip()

    @staticmethod
    def _clean_line(text: str) -> str:
        text = str(text or "").strip()
        text = re.sub(r"^\s*[-*•]+\s*", "", text)
        text = re.sub(r"^\s*\d+[).、：:]\s*", "", text)
        text = text.strip(" \t\r\n'\"`，。；;")
        return text.strip()

    def _parse_rewrite_output(self, raw_text: str, *, original_query: str, num_rewrites: int) -> List[str]:
        lines = []
        for raw_line in str(raw_text or "").splitlines():
            line = self._clean_line(raw_line)
            if not line:
                continue
            if line.startswith("[") and line.endswith("]"):
                line = self._clean_line(line.strip("[]"))
            if any(x in line for x in ("以下", "查询改写", "改写结果", "输出", "答案")) and len(line) < 30:
                continue
            lines.append(line)

        if len(lines) <= 1:
            # Some local models ignore line breaks. Split common Chinese separators.
            pieces = re.split(r"[；;]|(?<=。)\s*", str(raw_text or ""))
            lines = [self._clean_line(x) for x in pieces if self._clean_line(x)]

        candidates = []
        for line in lines:
            if len(line) < 4:
                continue
            if line == original_query:
                continue
            candidates.append(line)
        return self._dedup_keep_order(candidates)[: max(0, int(num_rewrites))]

    def _rewrite_queries(self, query: str, num_rewrites: int) -> tuple[List[str], Dict[str, Any]]:
        meta: Dict[str, Any] = {
            "method": "llm" if self._llm_available() else "deterministic_fallback",
            "latency_ms": None,
            "raw_output": None,
            "fallback_used": False,
            "fallback_reason": None,
        }
        requested = max(0, int(num_rewrites))
        if requested <= 0:
            return [], meta

        if self._llm_available():
            system_prompt = "你是企业级 RAG 检索查询改写器。你的任务是生成检索查询，不是回答问题。"
            prompt = (
                "请为下面的用户问题生成 RAG-Fusion 使用的检索查询改写。\n"
                "要求：\n"
                f"1. 生成 {requested} 条。\n"
                "2. 每条查询覆盖不同检索视角，例如业务需求、架构模块、流程阶段、验收标准、风险合规。\n"
                "3. 保留原问题核心实体，不要编造具体事实。\n"
                "4. 每行只输出一条查询，不要编号，不要解释。\n\n"
                f"用户问题：{query}"
            )
            try:
                t0 = self.timer.now()
                raw = self._call_llm(
                    prompt,
                    system_prompt=system_prompt,
                    max_new_tokens=int(self.generation_params.get("rewrite_max_new_tokens", max(96, requested * 64))),
                    temperature=0.1,
                    top_p=0.9,
                    do_sample=False,
                )
                meta["latency_ms"] = elapsed_ms(self.timer, t0)
                meta["raw_output"] = raw
                rewrites = self._parse_rewrite_output(raw, original_query=query, num_rewrites=requested)
                if rewrites:
                    meta["parsed_count"] = len(rewrites)
                    return rewrites, meta
                raise ValueError("LLM rewrite output produced no valid query")
            except Exception as exc:
                if not self.fallback_to_deterministic:
                    raise
                meta["fallback_used"] = True
                meta["fallback_reason"] = f"{exc.__class__.__name__}: {exc}"

        rewrites = self._deterministic_rewrite_queries(query=query, num_rewrites=requested)
        meta["method"] = "deterministic_fallback"
        meta["parsed_count"] = len(rewrites)
        return rewrites, meta

    def _build_hypothetical_document(self, query: str) -> tuple[Optional[str], Dict[str, Any]]:
        meta: Dict[str, Any] = {
            "method": "llm" if self._llm_available() else "deterministic_fallback",
            "latency_ms": None,
            "raw_output": None,
            "fallback_used": False,
            "fallback_reason": None,
        }

        if self._llm_available():
            system_prompt = "你是 HyDE 假想文档生成器。你的任务是生成用于检索的假想资料，不是最终回答。"
            prompt = (
                "请根据用户问题生成一段 HyDE 假想文档，用于向量检索。\n"
                "要求：\n"
                "1. 写成一段企业知识库资料风格的中文文本。\n"
                "2. 覆盖可能相关的概念、流程、模块、验收、风险、引用依据。\n"
                "3. 不要声称具体项目事实已经存在，不要输出引用编号。\n"
                "4. 长度控制在 200 到 350 个汉字。\n"
                "5. 只输出假想文档正文，不要解释。\n\n"
                f"用户问题：{query}"
            )
            try:
                t0 = self.timer.now()
                raw = self._call_llm(
                    prompt,
                    system_prompt=system_prompt,
                    max_new_tokens=int(self.generation_params.get("hyde_max_new_tokens", 256)),
                    temperature=0.1,
                    top_p=0.9,
                    do_sample=False,
                )
                meta["latency_ms"] = elapsed_ms(self.timer, t0)
                meta["raw_output"] = raw
                hyde = self._clean_hyde_output(raw)
                if hyde:
                    meta["char_count"] = len(hyde)
                    return hyde, meta
                raise ValueError("LLM HyDE output is empty")
            except Exception as exc:
                if not self.fallback_to_deterministic:
                    raise
                meta["fallback_used"] = True
                meta["fallback_reason"] = f"{exc.__class__.__name__}: {exc}"

        hyde = self._deterministic_hypothetical_document(query)
        meta["method"] = "deterministic_fallback"
        meta["char_count"] = len(hyde)
        return hyde, meta

    @staticmethod
    def _clean_hyde_output(raw_text: str) -> str:
        text = str(raw_text or "").strip()
        text = re.sub(r"^\s*(HyDE|假想文档|假设文档|正文)\s*[:：]\s*", "", text, flags=re.IGNORECASE)
        text = text.strip(" \t\r\n'\"`")
        return text

    def _deterministic_rewrite_queries(self, query: str, num_rewrites: int) -> List[str]:
        templates = [
            "{q} 的背景、目标、范围、约束、输入输出和验收要求",
            "{q} 涉及的关键概念、组成部分、处理流程、依赖关系和边界条件",
            "{q} 的实施步骤、风险、合规要求、质量标准和待确认信息",
            "{q} 的相关事实、数据依据、历史案例、规范条款和可追溯证据",
            "{q} 的常见问题、异常处理、评估指标、运维要求和改进建议",
        ]
        rewrites = [tpl.format(q=query) for tpl in templates]
        return self._dedup_keep_order(rewrites[: max(0, int(num_rewrites))])

    @staticmethod
    def _deterministic_hypothetical_document(query: str) -> str:
        return (
            f"这是一段与问题《{query}》高度相关的知识资料。"
            f"资料可能包含背景、目标、范围、约束、关键概念、组成部分、处理流程、"
            f"输入输出、事实依据、规范条款、风险控制、质量标准、验收要求和实施建议。"
            f"内容应围绕问题本身展开，并区分已知事实、外部依据和待确认信息。"
        )
